# ansible-playbook main.yml -i hosts --tags docker_apps
---
- hosts: epsilon
  become: yes
  become_method: sudo
  roles:
    - docker
    - docker-compose
    - mergerfs
    - snapraid
    - epsilon
