---

- name: install packages required by docker-compose
  apt:
    name: [ python-setuptools ]
    state: present
    update_cache: yes

#- name: Installing dependencies
#  easy_install:
#    name: pip

- name: install pip apt 
  apt:
    name: [ python3-pip ]
    state: present
    update_cache: yes

- name: Installing docker compose
  pip:
    name: docker-compose
    version: "{{ docker_compose_version if docker_compose_version else omit }}"
    state: present
